### ISSUE TITLE
HUGE ERROR when compiling in source code

### ISSUE THREAD

**Issue by ghost** [PocketMine/PocketMine-SPL#3]
Warning: require_once(C:\Users\Eliott\Desktop\PocketMine-MP-master\src\spl\ThreadedFactory.php): failed to open stream: No such file or directory in C:\Users\Eliott\Desktop\PocketMine-MP-master\src\pocketmine\PocketMine.php on line 101

Call Stack:
    0.0003     124704   1. {main}() C:\Users\Eliott\Desktop\PocketMine-MP-master\src\pocketmine\PocketMine.php:0

Fatal error: require_once(): Failed opening required 'C:\Users\Eliott\Desktop\PocketMine-MP-master\src\spl\ThreadedFactory.php' (include_path='.;.\ext') in C:\Users\Eliott\Desktop\PocketMine-MP-master\src\pocketmine\PocketMine.php on line 101

Call Stack:
    0.0003     124704   1. {main}() C:\Users\Eliott\Desktop\PocketMine-MP-master\src\pocketmine\PocketMine.php:0

bin\php\php.exe: Exit 255

**Comment by ghost** [comment]
seriously anyone?

**Comment by ghost** [comment]
I still can't chat It comes up as "chat.type.text" and when i get the phar of the source- the chat works. Doesn't get weirder than that.

**Comment by PEMapModder** [comment]
PocketMine uses d59c0f673455f02b2620853f3fa6290d63ffd960 instead of the latest version.
